---
driver_plugin: vagrant
driver_config:
  box: opscode-centos-6.4
  box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  network:
  - ["forwarded_port", { guest: 8080, host: 8081 }]

platforms:
- name: centos-6.4-chef-10
  driver_config:
    require_chef_omnibus: 10.16.2
- name: centos-6.4-chef-11
  driver_config:
    require_chef_omnibus: 11.4.4

suites:
- name: default
  run_list: ["recipe[jenkins]"]
  attributes: {}
